/**
 * The only desktop channels exposed by the bootstrap bridge. This module must
 * stay dependency-free so it can also be loaded from a sandboxed preload.
 */
export const IPC_CHANNELS = {
  runtimeGetInfo: "runtime.get_info",
  projectAdd: "project.add",
  projectRemove: "project.remove",
  projectRename: "project.rename",
  projectReorder: "project.reorder",
  projectSetPinned: "project.set_pinned",
  projectList: "project.list",
  projectListEntries: "project.list_entries",
  projectCreateEntry: "project.create_entry",
  projectReadFile: "project.read_file",
  conversationList: "conversation.list",
  conversationCreate: "conversation.create",
  conversationSelectWorkspace: "conversation.select_workspace",
  conversationClearWorkspace: "conversation.clear_workspace",
  conversationFork: "conversation.fork",
  conversationListForks: "conversation.list_forks",
  conversationRename: "conversation.rename",
  conversationReorder: "conversation.reorder",
  conversationSetProject: "conversation.set_project",
  conversationSetArchived: "conversation.set_archived",
  conversationSetPinned: "conversation.set_pinned",
  conversationDelete: "conversation.delete",
  conversationListTimeline: "conversation.list_timeline",
  conversationGetTaskList: "conversation.get_task_list",
  conversationCloseTaskList: "conversation.close_task_list",
  conversationDeleteTaskList: "conversation.delete_task_list",
  conversationMarkResultViewed: "conversation.mark_result_viewed",
  conversationGetContextUsage: "conversation.get_context_usage",
  conversationChooseAttachments: "conversation.choose_attachments",
  conversationListDraftAttachments: "conversation.list_draft_attachments",
  conversationRemoveAttachment: "conversation.remove_attachment",
  conversationSendMessage: "conversation.send_message",
  conversationReplaceLatestMessage: "conversation.replace_latest_message",
  conversationListPendingMessages: "conversation.list_pending_messages",
  conversationPromotePendingMessage: "conversation.promote_pending_message",
  conversationDeletePendingMessage: "conversation.delete_pending_message",
  conversationUpdatePendingMessage: "conversation.update_pending_message",
  conversationReorderPendingMessages: "conversation.reorder_pending_messages",
  conversationCancelRun: "conversation.cancel_run",
  conversationApproveToolChange: "conversation.approve_tool_change",
  conversationRunEvent: "conversation.run_event",
  modelGetApiKey: "model.get_api_key",
  modelGetCatalog: "model.get_catalog",
  modelGetStatus: "model.get_status",
  modelDiscover: "model.discover",
  modelTestConnection: "model.test_connection",
  modelSaveConfiguration: "model.save_configuration",
  modelSetDefault: "model.set_default",
  contextCompressionGetConfiguration: "context_compression.get_configuration",
  contextCompressionSaveConfiguration: "context_compression.save_configuration",
  applicationSettingsGetConfiguration: "application_settings.get_configuration",
  applicationSettingsSaveConfiguration: "application_settings.save_configuration",
  terminalGetConfiguration: "terminal.get_configuration",
  terminalSaveConfiguration: "terminal.save_configuration",
  integrationGetConfiguration: "integration.get_configuration",
  integrationSaveConfiguration: "integration.save_configuration",
  skillCreateDocument: "skill.create_document",
  skillChooseDirectory: "skill.choose_directory",
  skillDiscoverDocuments: "skill.discover_documents",
  skillImportDocument: "skill.import_document",
  skillReadDocument: "skill.read_document",
  skillSaveDocument: "skill.save_document",
  configurationWorkspaceListEntries: "configuration_workspace.list_entries",
  configurationWorkspaceReadFile: "configuration_workspace.read_file",
  configurationWorkspaceCreateEntry: "configuration_workspace.create_entry",
  configurationWorkspaceWriteFile: "configuration_workspace.write_file",
  configurationWorkspaceDeleteEntry: "configuration_workspace.delete_entry",
  windowGetState: "window.get_state",
  windowMinimize: "window.minimize",
  windowToggleMaximize: "window.toggle_maximize",
  windowClose: "window.close",
  windowStateChanged: "window.state_changed"
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
